### ISSUE TITLE
Add section to README.md on adding the SDK as a dependency in a Java project

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-scala-analytics-sdk#10]
I assume you need to specify the cross-version suffix (e.g. `_2.10`) when making the SDK a dependency in a POM file or using it from Zeppelin. This is probably sufficiently non-obvious to merit explicit documentation.

**Comment by chuwy** [comment]
Closing as this was done as part of #29

**Comment by alexanderdean** [comment]
Good point!
