### ISSUE TITLE
Add benchmarking module

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#108]
For reference https://github.com/snowplow/enrich/issues/370

**Comment by chuwy** [comment]
https://github.com/snowplow/snowplow-scala-analytics-sdk/issues/107 is the first target for benchmarking.

**Comment by chuwy** [comment]
Another good candidate for micro-benchmarks - [`atomic`](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/5efd96cbfd417e5aabab68ad3616029a49decda7/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/Event.scala#L196) can be rewritten as `toJsonMap - Set("contexts", "unstruct_event", "derived_contexts")`. Wondering if this version will be more performant.

**Comment by chuwy** [comment]
Third one - [`ordered`](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/5efd96cbfd417e5aabab68ad3616029a49decda7/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/Event.scala#L203) can be implemented as:

```scala
def ordered: Iterable[(String, Json)] =
  this.asJsonObject.toIterable
```

Not 100% sure that implementation is identical (and type is certainly not), but wondering if we can add it as an option.

**Comment by benjben** [comment]
Thanks for all the details @chuwy !

**Comment by benjben** [comment]
`atomic` without the `-- Set()`:

```
[info] Result "com.snowplowanalytics.snowplow.analytics.scalasdk.benchmark.BenchmarkAnalyticsSDK.atomic":
[info]   0.366 ±(99.9%) 0.022 us/op [Average]
[info]   (min, avg, max) = (0.319, 0.366, 0.434), stdev = 0.025
[info]   CI (99.9%): [0.345, 0.388] (assumes normal distribution)
[info] # Run complete. Total time: 00:08:4
```

With it:

```
[info] Result "com.snowplowanalytics.snowplow.analytics.scalasdk.benchmark.BenchmarkAnalyticsSDK.atomic":
[info]   0.589 ±(99.9%) 0.012 us/op [Average]
[info]   (min, avg, max) = (0.566, 0.589, 0.616), stdev = 0.014
[info]   CI (99.9%): [0.577, 0.601] (assumes normal distribution)
[info] # Run complete. Total time: 00:08:42
```

Surprisingly enough the first one is more performant
