### ISSUE TITLE
JSON Event Transformer: don't add null unstruct_event and contexts fields to output

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-scala-analytics-sdk#11]
When a field in the TSV is empty, we currently set it to `null` in the output JSON rather than omitting it entirely. We even do this for the `unstruct_event` and `contexts` fields - if the unstruct_event field of the TSV is nonempty, the output JSON will contain `{"unstruct_event": null}`. This doesn't really make sense, since when an event is unstructured, the output JSON won't have any `unstruct_event` field - instead it will have something like a `unstruct_event_com_snowplowanalytics_snowplow_link_click_1` field.

https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/d1a6d234c934249471a71090271aa582f6cd3609/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/json/EventTransformer.scala#L199

**Comment by alexanderdean** [comment]
What do we set `unstruct_event` to if the field is *not* null (i.e. is populated)?

**Comment by fblundun** [comment]
Nothing - in that case, there is no `unstruct_event` field in the output.

**Comment by alexanderdean** [comment]
Interesting - so are we using `unstruct_event` null as a kind of placeholder to flag that the user shouldn't go looking for a `unstruct_event_...`?

**Comment by alexanderdean** [comment]
To put it another way - isn't the inconsistency more on our handling of a not-null `unstruct_event` than a null one? The treatment of any null field seems to be consistent currently.

**Comment by fblundun** [comment]
At the moment it can be used for that purpose, although this wasn't an intentional feature - just a failure to notice that the field would be set.

I can't remember why we originally decided to set null for empty fields rather than having a nonexistent field. Possibly it was to make it easier to tell which version of the canonical event model was used to create a given enriched event JSON?

The current treatment is consistent in that whenever a given field of the TSV is an empty string, a null field whose name is equal to the name of that field appears in the output.

The current treatment is inconsistent in that it is not the case that for any input TSV, for any null property in the output JSON for that input TSV, there exists an input TSV such that its output JSON would have a property with the same name but with a non-null value. Sometimes a null property (`contexts` or `unstruct_event`) will be appear in the output even though the property with that name could never have a non-null value. For any input field other than `contexts` and `unstruct_event`, the property in the output which is null if the input field is empty has the same name as the property in the output which is not null if the input field is not empty.

Note also that we do not set the "geo_location" field in the output at all (not even to null) unless the "latitude" and "longitude" fields both exist.

**Comment by alexanderdean** [comment]
Can you propose a new treatment which is more consistent in this thread? Maybe using a Markdown table...

**Comment by fblundun** [comment]
Here's what I'm suggesting.

#### For contexts, derived_contexts and untruct_event fields:

If `contexts` field is empty: do nothing
If `contexts` field is nonempty: build and add a `contexts_${vendor}_${name}_${model}` property to the output

#### For all other fields:

If `app_id` field is empty: add a null `app_id` property to the output (alternatively, do nothing - this would considerably reduce the size of the output, and I'm not sure what benefit we get from putting null fields in the JSON)
If `app_id` field is nonempty: add it to the output

**Comment by alexanderdean** [comment]
Okay - I think let's do nothing if *any* POJO field is empty - it will keep the size of the entity down and shouldn't impact analytics...

**Comment by fblundun** [comment]
I agree!

**Comment by alexanderdean** [comment]
Updated approach based on @fblundun and me agreeing in April last year:

**If a field is empty: ** do not add to output

**If a field is non-empty: **

*For contexts, derived_contexts and untruct_event fields:* build and add a `contexts_${vendor}_${name}_${model}` property to the output

*For any other field*: add it to the output verbatim

**Comment by alexanderdean** [comment]
Let's come back to this later in the release @chuwy!

**Comment by chuwy** [comment]
After testing this with spark, turned out nullable POJO fields have it's purpose - without them Spark cannot infer valid DataFrame schema. 

Example: we're querying dataset where `se_label != NULL` and getting very small amount of results, then suddenly dataset appears without single `se_label` at all and we get runtime exception.

So, I reverted this to be original @fblundun proposal - just remove contexts and unstruct_event properties that are always nulll or non-existent.

**Comment by alexanderdean** [comment]
I agree with the updated plan.

However, the DataFrame inference problem you raise is obviously much more serious than what you describe - because this will apply to **any** self-describing event or custom context which is not predictably available in a given dataset...

**Comment by chuwy** [comment]
There's way to set dataframe schema programmatically, deriving it from JSON Schema, which is unfortunately looks like very challenging task.

**Comment by alexanderdean** [comment]
Yes it feels like this is where we will get to eventually...
