### ISSUE TITLE
Allow empty custom contexts

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#21]
[Unnecessary check](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/66bd8d49e05c883473841bbc3127c1688c655074/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/json/JsonShredder.scala#L175) should be removed. As per https://github.com/snowplow/snowplow/issues/2927.

This looks like reminder that we should allow JSON Schemas to be single source of truth in sake of typesafety.

**Comment by alexanderdean** [comment]
This should be scheduled as it is causing valid events (e.g. from the Ruby Tracker, which does not elide empty context arrays until https://github.com/snowplow/snowplow-ruby-tracker/issues/104) to be rejected.

**Comment by chuwy** [comment]
Had to be closed by https://github.com/snowplow/snowplow-scala-analytics-sdk/commit/47284c672f9a9144efb2d2a9d1f7b6acda5b8faa, but PR #27 was referenced. Closing.
