### ISSUE TITLE
Use standard regular expression for schema URIs

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#22]
We need to make all apps using Iglu subsystem to have same regular expression to match URI and FS paths for schemas. 

Currently we have best matching regular expression in [Iglu Core](https://github.com/snowplow/iglu/blob/master/0-common/scala-core/src/main/scala/com.snowplowanalytics.iglu/core/SchemaKey.scala#L55)

Same regex was proposed for Iglu Central: https://github.com/snowplow/iglu-central/issues/288 (patch tickets: https://github.com/snowplow/iglu-central/issues/490 and https://github.com/snowplow/iglu-central/issues/491).

Best solution would be just to include iglu core as part Analytics SDK (and patch schemas in Iglu Central). We made regex in iglu core public for exact this reasons.

**Comment by clarkeandrew** [comment]
I created a pull request here : https://github.com/snowplow/snowplow-scala-analytics-sdk/pull/23 with the fix that we are using to get around the lack of hyphen in schema name support.
