### ISSUE TITLE
Figure out how to use shapeless to strongly type our heterogenous events/contexts

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-analytics-sdk#3]
https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0

**Comment by alexanderdean** [comment]
Would love thoughts from @fblundun, @chuwy, @ninjabear on this...

**Comment by chuwy** [comment]
Was implemented as part of #53. Closing.
