### ISSUE TITLE
Add transformWithInventory to the JSON EventTransformer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-analytics-sdk#34]
The current signature is:

```scala
def transform(line: String): ValidatedEvent
```

where:

```scala
type ValidatedEvent = ValidationNel[String, String]
```

I want us to add a new type:

```scala
type ValidatedEventWithInventory = ValidationNel[String, Tuple2[String, Set[Tuple2[ShredPrefix, String]]]]
```

and add the function:

```scala
def transformWithInventory(line: String): ValidatedEventWithInventory
```

**ANTON TO REPLACE INNERMOST TUPLE2 WITH A CASE CLASS**

where the addition `Set[Tuple2[ShredPrefix, String]]` is the set of entities (self-describing events and custom contexts) which were added to this JSON through shredding. The Tuple2 contains:

* _1: the ShredPrefix ADT
* _2: the Iglu schema URI

Here is the extension to the [test suite](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/master/src/test/scala/com.snowplowanalytics.snowplow.analytics.scalasdk.json/EventTransformerSpec.scala) that should pass:

**ANTON TO UPDATE THE EXAMPLE BELOW**

```scala
val (json, inventory) = parse(jsonStr)

inventory must_== Set("contexts_org_schema_web_page_1", "contexts_org_w3_performance_timing_1", "unstruct_event_com_snowplowanalytics_snowplow_link_click_1", "contexts_com_snowplowanalytics_snowplow_ua_parser_context_1")
```

**Comment by alexanderdean** [comment]
Hey @chuwy - how much work is this feature?

**Comment by chuwy** [comment]
We already extract this data in JsonShredder, so I think it would take too much efforts and fits into 0.2.0.

**Comment by alexanderdean** [comment]
This is required for Project Strawberry

**Comment by alexanderdean** [comment]
Scheduled!
