### ISSUE TITLE
Fix non-merging matching contexts 

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#44]
Having two items of same context, but with different revision/addition they result in two distinct keys in JSON output object: 

Input:
```
[
  iglu:org.acme/context_one/jsonschema/1-0-0, 
  iglu:org.acme/context_one/jsonschema/1-0-1
]
```

Output:
```json
{
  "contexts_org_acme_context_one_1" : [ {
    "item" : 1
  } ],
  "contexts_org_acme_context_one_1" : [ {
    "item" : 2
  } ]
}
```

Works fine for equal schema versions.

Scheduling for urgent 0.2.1 bugfix release.

**Comment by alexanderdean** [comment]
AHA!
