### ISSUE TITLE
Fix specification assuming unstruct_event field contains contexts envelope

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#57]
https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/master/src/test/scala/com.snowplowanalytics.snowplow.analytics.scalasdk.json/EventTransformerSpec.scala#L34

It shouldn't introduce any bugs in tests, just makes specification slightly confusing. Envelope should be [unstruct_event](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0)

**Comment by alexanderdean** [comment]
How does that test pass?

**Comment by chuwy** [comment]
Algorithm does not know about proper schema name.
