### ISSUE TITLE
Fix non-flattening algorithm not returning inventory items

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-analytics-sdk#58]
In 0.3.1 we introduced an API without flattening self-describing JSONs. However, this function always returns an empty inventory, which means all our events are missing their attached schema keys.

**Comment by knservis** [comment]
It seems to me that the schema keys are only useful when you flatten all keys, so that you can tell which schemas are found in the event. There was no need for that feature in unflattened version. Does someone require this?

**Comment by knservis** [comment]
Possibly `def getValidatedJsonEvent(event: Array[String], flatten: Boolean): Validated[(Set[InventoryItem], JObject)]` should be private and the public one should be a new function with the signature: `getUnflattenedJsonEvent(event: Array[String]): Validated[JObject]`

**Comment by chuwy** [comment]
* API is subject to change as per https://github.com/snowplow/snowplow-scala-analytics-sdk/issues/53
* This is a bug
