### ISSUE TITLE
Bump scalacheck to 1.14.0

### ISSUE THREAD

**Issue by rzats** [snowplow/snowplow-scala-analytics-sdk#65]

**Comment by chuwy** [comment]
I'm wondering if we actually use scalacheck in this SDK @rzats?

**Comment by rzats** [comment]
@chuwy it's only used for [SyntaxSpec](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/master/src/test/scala/com.snowplowanalytics.snowplow.analytics.scalasdk.json/SyntaxSpec.scala), which I think is about to be deprecated. So yes it can be removed along with EventTransformer, json4s etc.

**Comment by chuwy** [comment]
Okay. But if you see any scenario where we can actually come up with property-based test specification - please add such spec. If not - agree, let's delete.
