### ISSUE TITLE
SBT StackOverflowError

### ISSUE THREAD

**Issue by NielsAlebregtse** [snowplow/snowplow-scala-analytics-sdk#77]
We are trying to incorporate the snowplow-scala-analytics-sdk into one of our projects. However, we keep running into a StackOverflowError when we try to compile our source code with sbt.
Trying a simple `sbt clean test` on a clone of the current sdk master repo yields the same error on my machine.

Can you give us some guidance how to use the new version of the snowplow-scala-analytics-sdk?

**Comment by chuwy** [comment]
Hi @NielsAlebregtse, that's very strange. What versions JDK and SBT you're using?

**Comment by bekiroguz** [comment]
Writing about the same problem: We use JDK8 and sbt 1.2.8. Apparently sbt compile started working again after passing `-Xss2M` parameter in SBT_OPTS env variable, or adding `-J-Xss2M` line to the sbtopts file located in /usr/local/etc/sbtopts in my macbook.

**Comment by bekiroguz** [comment]
This should be related to the circe library macro's trying to process the Event case class with 131 fields.

**Comment by chuwy** [comment]
Thanks @bekiroguz. Yes, codec derivation is an expensive operation. I was just surprised because it worked on multiple machines we tried before, without any issues. Closing this.
