### ISSUE TITLE
Add function to create minimal event

### ISSUE THREAD

**Issue by aldemirenes** [snowplow/snowplow-scala-analytics-sdk#81]
Similar implementation can be found in [here](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/0.2.0-rc8/loader/src/test/scala/com/snowplowanalytics/snowplow/storage/bigquery/loader/SpecHelpers.scala#L95).

**Comment by dilyand** [comment]
A bare-bones event that only has values for the required fields and `None` for all optional fields.

**Comment by chuwy** [comment]
We forgot "`close`" on this one, @dilyand.
